version: '3'

services:
  kipartbase:
    build: kipartbase
    restart: unless-stopped
    ports:
      - 8100:8100
    environment:
     - KIPARTBASE_PATH=/opt
    volumes:
      - ~/.kipartman/db.sqlite3:/opt/db.sqlite3
      - ~/.kipartman/files:/opt/files
