swagger: "2.0"
info:
  version: 1.0.0
  title: Kipartman
  description: Kipartman api specifications
  termsOfService: http://swagger.io/terms/
  contact:
    name: Sebastien Besombes
    email: --
    url: https://github.com/turdusmerula/kipartman
  license:
    name: GPL V3
    url: https://raw.githubusercontent.com/turdusmerula/kipartman/master/LICENSE
host: localhost:8200
#host: kipartman.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /parts/categories:
    get:
      description: Return all categories for parts
      operationId: findPartsCategories
      responses:
        "200":
          description: List of categories
          schema:
            type: array
            items:
              $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
    post:
      description: Creates a new part category
      operationId: addPartsCategory
      parameters:
        - name: category
          in: body
          description: Category to add
          required: true
          schema:
            $ref: './part/category/PartCategoryNew.yaml'
      responses:
        "200":
          description: Created category
          schema:
            $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
  /parts/categories/{category_id}:
    get:
      description: Return a part category
      operationId: findPartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Categories
          schema:
            $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update part category
      operationId: updatePartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
        - name: category
          in: body
          description: Category to update
          required: true
          schema:
            $ref: './part/category/PartCategoryNew.yaml'
      responses:
        "200":
          description: Updated pärt category
          schema:
            $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete part category
      operationId: deletePartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /parts:
    get:
      description: Return all parts
      operationId: findParts
      parameters:
        - name: category
          in: query
          description: Filter by category
          type: integer
          format: int64
        - name: with_offers
          in: query
          description: Include offers in answer
          type: boolean
        - name: with_parameters
          in: query
          description: Include parameters in answer
          type: boolean
        - name: with_childs
          in: query
          description: Include childs in answer
          type: boolean
        - name: with_distributors
          in: query
          description: Include distributors in answer
          type: boolean
        - name: with_manufacturers
          in: query
          description: Include manufacturers in answer
          type: boolean
        - name: search
          in: query
          description: Search for parts matching pattern
          type: string
      responses:
        "200":
          description: List of parts
          schema:
            type: array
            items:
              $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Creates a new part
      operationId: addPart
      parameters:
        - name: part
          in: body
          description: Part to add
          required: true
          schema:
            $ref: './part/PartNew.yaml'
      responses:
        "200":
          description: Created part
          schema:
            $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /parts/{part_id}:
    get:
      description: Return a part
      operationId: findPart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: with_offers
          in: query
          description: Include offers in answer
          type: boolean
        - name: with_parameters
          in: query
          description: Include parameters in answer
          type: boolean
        - name: with_childs
          in: query
          description: Include childs in answer
          type: boolean
        - name: with_distributors
          in: query
          description: Include distributors in answer
          type: boolean
        - name: with_manufacturers
          in: query
          description: Include manufacturers in answer
          type: boolean
      responses:
        "200":
          description: Categories
          schema:
            $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update part
      operationId: updatePart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: part
          in: body
          description: Part to update
          required: true
          schema:
            $ref: './part/Part.yaml'
      responses:
        "200":
          description: Updated pärt
          schema:
            $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete part
      operationId: deletePart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'



  /units:    
    get:
      description: Return list of units
      operationId: findUnits
      parameters:
        - name: symbol
          in: query
          description: Search symbol
          type: string
      responses:
        "200":
          description: Units
          schema:
            type: array
            items:
              $ref: './unit/Unit.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /units/{unit_id}:    
    get:
      description: Return a unit
      operationId: findUnit
      parameters:
        - $ref: './types/unit_id.yaml#/unit_id'
      responses:
        "200":
          description: Unit
          schema:
            $ref: './unit/Unit.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /unitprefixes:    
    get:
      description: Return list of unit prefixes
      operationId: findUnitPrefixes
      parameters:
        - name: symbol
          in: query
          description: Search prefix symbol
          type: string
      responses:
        "200":
          description: Unit prefixes
          schema:
            type: array
            items:
              $ref: './unit/UnitPrefix.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /unitprefixes/{unit_prefix_id}:    
    get:
      description: Return a unit prefixes
      operationId: findUnitPrefix
      parameters:
        - $ref: './types/unit_prefix_id.yaml#/unit_prefix_id'
      responses:
        "200":
          description: Unit prefix
          schema:
            $ref: './unit/UnitPrefix.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'


  /footprints/categories:
    get:
      description: Return all categories for footprints
      operationId: findFootprintsCategories
      responses:
        "200":
          description: List of categories
          schema:
            type: array
            items:
              $ref: './footprint/category/FootprintCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
    post:
      description: Creates a new footprint category
      operationId: addFootprintsCategory
      parameters:
        - name: category
          in: body
          description: Category to add
          required: true
          schema:
            $ref: './footprint/category/FootprintCategoryNew.yaml'
      responses:
        "200":
          description: Created category
          schema:
            $ref: './footprint/category/FootprintCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
  /footprints/categories/{category_id}:
    get:
      description: Return a footprint category
      operationId: findFootprintsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Categories
          schema:
            $ref: './footprint/category/FootprintCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update footprint category
      operationId: updateFootprintsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
        - name: category
          in: body
          description: Category to update
          required: true
          schema:
            $ref: './footprint/category/FootprintCategoryNew.yaml'
      responses:
        "200":
          description: Updated pärt category
          schema:
            $ref: './footprint/category/FootprintCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete footprint category
      operationId: deleteFootprintsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /footprints:
    get:
      description: Return all footprints
      operationId: findFootprints
      parameters:
        - name: category
          in: query
          description: Filter by category
          type: integer
          format: int64
        - name: search
          in: query
          description: Search for footprint matching pattern
          type: string
      responses:
        "200":
          description: List of footprints
          schema:
            type: array
            items:
              $ref: './footprint/Footprint.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Creates a new footprint
      operationId: addFootprint
      parameters:
        - name: footprint
          in: body
          description: Footprint to add
          required: true
          schema:
            $ref: './footprint/FootprintNew.yaml'
      responses:
        "200":
          description: Created footprint
          schema:
            $ref: './footprint/Footprint.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /footprints/{footprint_id}:
    get:
      description: Return a footprint
      operationId: findFootprint
      parameters:
        - $ref: './types/footprint_id.yaml#/footprint_id'
      responses:
        "200":
          description: Categories
          schema:
            $ref: './footprint/Footprint.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update footprint
      operationId: updateFootprint
      parameters:
        - $ref: './types/footprint_id.yaml#/footprint_id'
        - name: footprint
          in: body
          description: Footprint to update
          required: true
          schema:
            $ref: './footprint/FootprintNew.yaml'
      responses:
        "200":
          description: Updated pärt
          schema:
            $ref: './footprint/Footprint.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete footprint
      operationId: deleteFootprint
      parameters:
        - $ref: './types/footprint_id.yaml#/footprint_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'



  /distributors:
    get:
      description: Return all distributors
      operationId: findDistributors
      parameters:
        - name: name
          in: query
          description: Search distributors matching name
          type: string      
      responses:
        "200":
          description: List of distributors
          schema:
            type: array
            items:
              $ref: './distributor/Distributor.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Creates a new distributor
      operationId: addDistributor
      parameters:
        - name: distributor
          in: body
          description: Distributor to add
          required: true
          schema:
            $ref: './distributor/DistributorNew.yaml'
      responses:
        "200":
          description: Created distributor
          schema:
            $ref: './distributor/Distributor.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
            
  /distributors/{distributor_id}:
    get:
      description: Return a distributor
      operationId: findDistributor
      parameters:
        - $ref: './types/distributor_id.yaml#/distributor_id'
      responses:
        "200":
          description: Distributors
          schema:
            $ref: './distributor/Distributor.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update a distributor
      operationId: updateDistributor
      parameters:
        - $ref: './types/distributor_id.yaml#/distributor_id'
        - name: category
          in: body
          description: Distributor to update
          required: true
          schema:
            $ref: './distributor/DistributorNew.yaml'
      responses:
        "200":
          description: Updated distributor
          schema:
            $ref: './distributor/Distributor.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete distributor
      operationId: deleteDistributor
      parameters:
        - $ref: './types/distributor_id.yaml#/distributor_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

            

  /manufacturers:
    get:
      description: Return all manufacturers
      operationId: findManufacturers
      parameters:
        - name: name
          in: query
          description: Search manufacturers matching name
          type: string      
      responses:
        "200":
          description: List of manufacturers
          schema:
            type: array
            items:
              $ref: './manufacturer/Manufacturer.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Creates a new manufacturer
      operationId: addManufacturer
      parameters:
        - name: manufacturer
          in: body
          description: Manufacturer to add
          required: true
          schema:
            $ref: './manufacturer/ManufacturerNew.yaml'
      responses:
        "200":
          description: Created manufacturer
          schema:
            $ref: './manufacturer/Manufacturer.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
            
  /manufacturers/{manufacturer_id}:
    get:
      description: Return a manufacturer
      operationId: findManufacturer
      parameters:
        - $ref: './types/manufacturer_id.yaml#/manufacturer_id'
      responses:
        "200":
          description: Manufacturer
          schema:
            $ref: './manufacturer/Manufacturer.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update a manufacturer
      operationId: updateManufacturer
      parameters:
        - $ref: './types/manufacturer_id.yaml#/manufacturer_id'
        - name: category
          in: body
          description: Manufacturer to update
          required: true
          schema:
            $ref: './manufacturer/ManufacturerNew.yaml'
      responses:
        "200":
          description: Updated manufacturer
          schema:
            $ref: './manufacturer/Manufacturer.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete manufacturer
      operationId: deleteManufacturer
      parameters:
        - $ref: './types/manufacturer_id.yaml#/manufacturer_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /upload:
    post:
      description: Upload a file.
      operationId: addUploadFile
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        "200":
          description: Path of updated file
          schema:
            $ref: './upload/UploadFile.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
