swagger: "2.0"
info:
  version: 1.0.0
  title: Kipartman
  description: Kipartman api specifications
  termsOfService: http://swagger.io/terms/
  contact:
    name: Sebastien Besombes
    email: --
    url: https://github.com/turdusmerula/kipartman
  license:
    name: GPL V3
    url: https://raw.githubusercontent.com/turdusmerula/kipartman/master/LICENSE
host: localhost:8200
#host: kipartman.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /parts/categories:
    get:
      description: Return all categories for parts
      operationId: findPartsCategories
      responses:
        "200":
          description: List of categories
          schema:
            type: array
            items:
              $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
    post:
      description: Creates a new part category
      operationId: addPartsCategory
      parameters:
        - name: category
          in: body
          description: Category to add
          required: true
          schema:
            $ref: './part/category/PartCategoryNew.yaml'
      responses:
        "200":
          description: Created category
          schema:
            $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
    
  /parts/categories/{category_id}:
    get:
      description: Return a part category
      operationId: findPartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Categories
          schema:
            type: array
            items:
              $ref: './part/category/PartCategoryTree.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update part category
      operationId: updatePartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
        - name: category
          in: body
          description: Category to update
          required: true
          schema:
            $ref: './part/category/PartCategoryNew.yaml'
      responses:
        "200":
          description: Updated pärt category
          schema:
            $ref: './part/category/PartCategory.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete part category
      operationId: deletePartsCategory
      parameters:
        - $ref: './types/category_id.yaml#/category_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /parts:
    get:
      description: Return all parts
      operationId: findParts
      responses:
        "200":
          description: List of parts
          schema:
            type: array
            items:
              $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Creates a new part
      operationId: addPart
      parameters:
        - name: part
          in: body
          description: Part to add
          required: true
          schema:
            $ref: './part/PartNew.yaml'
      responses:
        "200":
          description: Created part
          schema:
            $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /parts/{part_id}:
    get:
      description: Return a part
      operationId: findPart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
      responses:
        "200":
          description: Categories
          schema:
            type: array
            items:
              $ref: './part/PartTree.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update part
      operationId: updatePart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: part
          in: body
          description: Part to update
          required: true
          schema:
            $ref: './part/PartNew.yaml'
      responses:
        "200":
          description: Updated pärt
          schema:
            $ref: './part/Part.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete part
      operationId: deletePart
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'


  /parts/{part_id}/parameters:    
    get:
      description: Return all parameters for part
      operationId: findPartParameters
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
      responses:
        "200":
          description: List of part parameters
          schema:
            type: array
            items:
              $ref: './part/parameter/PartParameter.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    post:
      description: Create some new part parameters
      operationId: addPartParameters
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: parameters
          in: body
          description: Parameters to add
          required: true
          schema:
            type: array
            items:
              $ref: './part/parameter/PartParameterNew.yaml'
      responses:
        "200":
          description: Created parameters
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete list of part parameters
      operationId: deletePartParameters
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: parameters
          in: body
          description: Parameters to delete
          required: true
          schema:
            type: array
            items:
              $ref: './part/parameter/PartParameterRef.yaml'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update list of part parameters
      operationId: updatePartParameters
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - name: parameters
          in: body
          description: Parameters to update
          required: true
          schema:
            type: array
            items:
              $ref: './part/parameter/PartParameter.yaml'
      responses:
        "200":
          description: Created parameters
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /parts/{part_id}/parameters/{parameter_id}:
    get:
      description: Return a part parameter
      operationId: findPartParameter
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - $ref: './types/parameter_id.yaml#/parameter_id'
      responses:
        "200":
          description: Parameter
          schema:
            type: array
            items:
              $ref: './part/parameter/PartParameter.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    put:
      description: Update part parameter
      operationId: updatePartParameter
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - $ref: './types/parameter_id.yaml#/parameter_id'
        - name: category
          in: body
          description: Parameter to update
          required: true
          schema:
            $ref: './part/parameter/PartParameterNew.yaml'
      responses:
        "200":
          description: Updated pärt parameter
          schema:
            $ref: './part/parameter/PartParameter.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

    delete:
      description: Delete part parameter
      operationId: deletePartParameter
      parameters:
        - $ref: './types/part_id.yaml#/part_id'
        - $ref: './types/parameter_id.yaml#/parameter_id'
      responses:
        "200":
          description: Deleted ok
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /units:    
    get:
      description: Return list of units
      operationId: findUnits
      responses:
        "200":
          description: Units
          schema:
            type: array
            items:
              $ref: './unit/Unit.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /units/{unit_id}:    
    get:
      description: Return a unit
      operationId: findUnit
      parameters:
        - $ref: './types/unit_id.yaml#/unit_id'
      responses:
        "200":
          description: Unit
          schema:
            $ref: './unit/Unit.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /unitprefixes:    
    get:
      description: Return list of unit prefixes
      operationId: findUnitPrefixes
      responses:
        "200":
          description: Unit prefixes
          schema:
            type: array
            items:
              $ref: './unit/UnitPrefix.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'

  /unitprefixes/{unit_prefix_id}:    
    get:
      description: Return a unit prefixes
      operationId: findUnitPrefix
      parameters:
        - $ref: './types/unit_prefix_id.yaml#/unit_prefix_id'
      responses:
        "200":
          description: Unit prefix
          schema:
            $ref: './unit/UnitPrefix.yaml'
        default:
          description: unexpected error
          schema:
            $ref: './Error.yaml'
